// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC7ysCP-R4Dkr0saMv7ZtA5srFgeVsUMk',
    appId: '1:436524335615:web:9e7cea9b95508b380927ca',
    messagingSenderId: '436524335615',
    projectId: 'connectme-7b192',
    authDomain: 'connectme-7b192.firebaseapp.com',
    storageBucket: 'connectme-7b192.firebasestorage.app',
    measurementId: 'G-GJ1WLP49XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMMyJpIi1LGyoLO5iyAmG5b8e0ewQehE',
    appId: '1:436524335615:android:0a64490cf57213ab0927ca',
    messagingSenderId: '436524335615',
    projectId: 'connectme-7b192',
    storageBucket: 'connectme-7b192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZkgqwaOWvMzwTQG_dtq6MXWXKc_3Wotk',
    appId: '1:436524335615:ios:090336e063f36cfb0927ca',
    messagingSenderId: '436524335615',
    projectId: 'connectme-7b192',
    storageBucket: 'connectme-7b192.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZkgqwaOWvMzwTQG_dtq6MXWXKc_3Wotk',
    appId: '1:436524335615:ios:090336e063f36cfb0927ca',
    messagingSenderId: '436524335615',
    projectId: 'connectme-7b192',
    storageBucket: 'connectme-7b192.firebasestorage.app',
    iosBundleId: 'com.example.connectmeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC7ysCP-R4Dkr0saMv7ZtA5srFgeVsUMk',
    appId: '1:436524335615:web:c3324b2afdab46a10927ca',
    messagingSenderId: '436524335615',
    projectId: 'connectme-7b192',
    authDomain: 'connectme-7b192.firebaseapp.com',
    storageBucket: 'connectme-7b192.firebasestorage.app',
    measurementId: 'G-6X5DMYRTHD',
  );
}
